customer_engine/urls.py
from rest_framework.routers import DefaultRouter
from  .views import AllDishesViewSet
from django.urls import path,include
from . import views
from .views import *

router = DefaultRouter()
router.register(r'all/dishes', AllDishesViewSet, basename ="all dishes")


urlpatterns = [
    path('', include(router.urls)),
    path('login/', LoginAPIView.as_view(), name='login'),
    path('verify-otp/', OTPVerifyAPI.as_view(), name='verify-otp'),
    path('send/otp/',views.SendOtpViews.as_view()),
    path('verify/otp/',views.VerifyOtpViews.as_view()),
    path('update/user/details/',views.UpdateUserDetailViews.as_view()),
    path('upload/image/',views.UploadImageView.as_view()),
    path('daily_calories/', DailyCaloryView.as_view(), name='daily_calories'),
    path('add/calory/', AddCaloryViews.as_view(), name='daily_calories'),
    path('customer-daily-calories/<str:date>/', CustomerDailyCaloriesView.as_view(), name='customer_daily_calories'),
    path('calorigram/<int:id>/', CalorigramView.as_view(), name='calorigram'),
    path('create-recipe/', CreateRecipe.as_view(), name='upload_recipe'),
    path('daily-calorigram/<str:date>/', DailyCalorigramView.as_view(), name='daily_calorigram'),
    path('get-dishes/', GetIngridientView.as_view(), name='get_dishes'),
    path('user-profile/', UserProfile.as_view(), name='user_profile'),
    path('user-profile-detail/', UserProfileDetails.as_view(), name='user_profile_detail'),

]

freelance_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.urls import re_path
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from django.conf import settings
from django.conf.urls.static import static


...

schema_view = get_schema_view(
   openapi.Info(
      title="API Documentation",
      default_version='v1',
      description="Send OTP and Verify OTP API",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@xyz.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/',include('customer_engine.urls')),
    path('',include('backoffice_engine.urls')),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]
# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer_engine/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import MaxValueValidator
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser, Group, Permission


class Customer(AbstractUser):
    image_url = models.URLField(max_length=200, blank=True, null=True)
    first_name = models.CharField(max_length=100,blank=True, null=True)
    last_name = models.CharField(max_length=100,blank=True, null=True)
    gender = models.CharField(max_length=100,blank=True, null=True)
    location = models.CharField(max_length=100,blank=True, null=True)
    address = models.CharField(max_length=500,blank=True, null=True)
    contact_number = models.CharField(max_length=15,blank=True, null=True)
    email = models.CharField(max_length=100,blank=True, null=True)
    date_of_birth = models.CharField(max_length=100,blank=True, null=True)
    age = models.IntegerField(blank=True, null=True)
    height = models.DecimalField(max_digits=5, decimal_places=2,blank=True, null=True)
    height_unit = models.CharField(max_length=10,blank=True, null=True)
    weight = models.DecimalField(max_digits=5, decimal_places=2,blank=True, null=True)
    weight_unit = models.CharField(max_length=10,blank=True, null=True)
    health_issue = models.CharField(max_length=1000,blank=True, null=True)
    other_issue = models.CharField(max_length=1000,blank=True, null=True)
    any_medication = models.CharField(max_length=500,blank=True, null=True)
    veg_nonveg = models.CharField(max_length=500,blank=True, null=True)
    profession = models.CharField(max_length=200,blank=True, null=True)
    help = models.CharField(max_length=500, blank=True, null=True)
    date = models.DateField(default=timezone.now)
    groups = models.ManyToManyField(
        Group,
        verbose_name='groups',  
        blank=True,
        related_name='user_profiles' 
    )
    user_permissions = models.ManyToManyField(
        Permission,
        verbose_name='user permissions',
        blank=True,
        related_name='user_profiles_permissions'
    )

    def __str__(self):
        return str(self.id)
    


class UserOTP(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    otp = models.IntegerField()


class CaloryCount(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    dish_type = models.CharField(max_length=100,blank=True,null = True)
    dish = models.IntegerField(null = True)
    calory = models.FloatField(default = 0.0)
    date = models.DateField(null=True,blank=True)
    total_calory = models.FloatField(default = 0.0)

    def __str__(self):
        return str(self.calory)
    

class DailySnacks(models.Model):
    TYPE_CHOICES = (
        ('breakfast', 'Breakfast'),
        ('lunch', 'Lunch'),
        ('dinner', 'Dinner'),
        ('evening_snacks', 'Evening Snacks'),
    )

    FOOD_CHOICES = (
        ('Vegetarian', 'Vegetarian'),
        ('Non Vegetarian', 'Non Vegetarian'),
        ('Eggetarian', 'Eggetarian'),
        ('Pescatarian', 'Pescatarian'),
        ('Pollotarian', 'Pollotarian'),
        ('Vegan', 'Vegan'),
    )

    DISH_CHOICES = (
        ('ANI', 'ANI'),
        ('Restaurent', 'Restaurent'),
        ('Fit4life', 'Fit4life'),
        ('OWN', 'OWN'),
    )

    meal_type = models.CharField(max_length=15, choices=TYPE_CHOICES, null=False, blank=False)
    food = models.CharField(max_length=200,null=True,blank=True)
    quantity = models.CharField(max_length=50, null=True)
    ingredients = models.CharField(max_length=255, null=True, blank=True)
    veg_nonveg_egg = models.CharField(max_length=30, choices=FOOD_CHOICES, null=False, blank=False)
    pral = models.FloatField(null=True, default=0.0)
    oil = models.FloatField(null=True, default=0.0)
    gl = models.FloatField(null=True, default=0.0)
    cals = models.FloatField(null=True, default=0.0)
    aaf_adj_prot = models.FloatField(null=True, default=0.0)
    carbs = models.FloatField(null=True, default=0.0)
    total_fat = models.FloatField(null=True, default=0.0)
    tdf = models.FloatField(null=True, default=0.0)
    sodium = models.FloatField(null=True, default=0.0)
    potassium = models.FloatField(null=True, default=0.0)
    phosphorus = models.FloatField(null=True, default=0.0)
    calcium = models.FloatField(null=True, default=0.0)
    magnesium = models.FloatField(null=True, default=0.0)
    total_eaa = models.FloatField(null=True, default=0.0)
    lysine = models.FloatField(null=True, default=0.0)
    gross_protein = models.FloatField(null=True, default=0.0)
    free_sugar = models.FloatField(null=True, default=0.0)
    aa_factor = models.FloatField(null=True, default=0.0)
    glucose = models.FloatField(null=True, default=0.0)
    dish = models.CharField(max_length=30, choices=DISH_CHOICES, null=False, blank=False)

    def __str__(self):
        return str(self.food)


class UserSnacks(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    dish = models.ForeignKey(DailySnacks, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class AddRecipe(models.Model):
    item_name = models.CharField(max_length=1000)
    sub_name = models.CharField(max_length=1000,null=True,blank=True)
    quantity_type = models.CharField(max_length=100,null=True,blank=True)
    quantity = models.FloatField(null=True,blank=True)
    quantity_help = models.CharField(max_length=200,null=True,blank=True)
    type_of_meal = models.CharField(max_length=100,null=True,blank=True)
    type_of_food = models.CharField(max_length=100,null=True,blank=True)
    health_condition = models.CharField(max_length=500,null=True,blank=True)

    def __str__(self):
        return self.item_name


class AddIngridient(models.Model):
    item = models.ForeignKey(AddRecipe, on_delete=models.CASCADE)
    ingridient_name = models.CharField(max_length=1000)
    quantity_type = models.CharField(max_length=100,null=True,blank=True)
    ingridient_quantity = models.FloatField(null=True)
    protein = models.FloatField(null=True,blank=True)
    calories = models.FloatField(null=True,blank=True)
    fat = models.FloatField(null=True,blank=True)
    carps = models.FloatField(null=True,blank=True)
    sugars = models.FloatField(null=True,blank=True)
    sodium = models.FloatField(null=True,blank=True)
    fiber = models.FloatField(null=True,blank=True)

    def __str__(self):
        return self.ingridient_name


class DailyRecipe(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    dishes = models.ForeignKey(DailySnacks, on_delete=models.CASCADE )
    

    def __str__(self):
        return self.food

class Dishes(models.Model):
    food = models.CharField(max_length=200,null=True,blank=True)
    price = models.CharField(max_length=10, null=True)
    oil = models.FloatField(null=True)
    gl = models.FloatField(null=True)
    useble_cals = models.FloatField(null=True)
    aaf_adj_prot = models.FloatField(null=True)
    carbs = models.FloatField(null=True)
    total_fat = models.FloatField(null=True)
    tdf = models.FloatField(null=True)
    sodium = models.FloatField(null=True)
    potassium = models.FloatField(null=True)
    phasphorous = models.FloatField(null=True)
    calcium = models.FloatField(null=True)
    magnecium = models.FloatField(null=True)
    total_eaa = models.FloatField(null=True)
    lysine = models.FloatField(null=True)
    gross_protine = models.FloatField(null=True)
    free_suger = models.FloatField(null=True)


    def __str__(self):
        return self.food



class Recipe(models.Model):
    image = models.TextField(null=True, blank=True)  # Requires Pillow library
    dish_name = models.CharField(max_length=255)
    TYPE_CHOICES = (
            ('breakfast', 'Breakfast'),
            ('lunch', 'Lunch'),
            ('dinner', 'Dinner'),
            ('evening_snacks', 'Evening Snacks'),
        )
    category = models.CharField(max_length=15, choices=TYPE_CHOICES, null=False, blank=False)
    TYPE_CHOICES = (
            ('gms', 'Breakfast'),
            ('ml', 'Lunch'),
            ('quantity', 'quantity'),
        )
    serving_size = models.CharField(max_length=15, choices=TYPE_CHOICES, null=False, blank=False)
  

class RecipeIngridient(models.Model):
    dishes = models.ForeignKey(Dishes, on_delete=models.CASCADE )
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE )
    quantity = models.FloatField(null=True,blank=True)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Fit4LifeIndia Admin Dashboard</title>
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="/static/images/favicon.png">
	<link rel="stylesheet" href="/static/vendor/chartist/css/chartist.min.css">
    <link href="/static/vendor/bootstrap-select/dist/css/bootstrap-select.min.css" rel="stylesheet">
	<link href="/static/vendor/owl-carousel/owl.carousel.css" rel="stylesheet">
    <link href="/static/vendor/datatables/css/jquery.dataTables.min.css" rel="stylesheet">
    <link href="/static/css/style.css" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&amp;family=Roboto:wght@100;300;400;500;700;900&amp;display=swap" rel="stylesheet">
    <style>
        {% block css %}{% endblock %}
    </style>
</head>

<body>

    <!--*******************
        Preloader start
    ********************-->
    <div id="preloader">
        <div class="sk-three-bounce">
            <div class="sk-child sk-bounce1"></div>
            <div class="sk-child sk-bounce2"></div>
            <div class="sk-child sk-bounce3"></div>
        </div>
    </div>
    <!--*******************
        Preloader end
    ********************-->

    <!--**********************************
        Main wrapper start
    ***********************************-->
    <div id="main-wrapper">

        <!--**********************************
            Nav header start
        ***********************************-->
        <div class="nav-header">
             <a href="{% url 'dashboard' %}" class="brand-logo">
                <img class="logo-abbr" src="/static/images/icon-logo.png" alt="">
                <img class="logo-compact" src="/static/images/logo.png" alt="">
                <img class="brand-title" src="/static/images/logo.png" alt="">
            </a>

            <div class="nav-control">
                <div class="hamburger">
                    <span class="line"></span><span class="line"></span><span class="line"></span>
                </div>
            </div>
        </div>
        <!--**********************************
            Nav header end
        ***********************************-->
		
		<!--**********************************
            Header start
        ***********************************-->
        <div class="header">
            <div class="header-content">
                <nav class="navbar navbar-expand">
                    <div class="collapse navbar-collapse justify-content-between">
                        <div class="header-left">
                            <div class="dashboard_bar">
								Dashboard
                            </div>
                        </div>
                        <ul class="navbar-nav header-right">
							<li class="nav-item">
								<div class="input-group search-area d-xl-inline-flex d-none">
									<div class="input-group-append">
										<span class="input-group-text"><a href="javascript:void(0)"><i class="flaticon-381-search-2"></i></a></span>
									</div>
									<input type="text" class="form-control" placeholder="Search here...">
								</div>
							</li>
                            <li class="nav-item dropdown header-profile">
                                <a class="nav-link" href="javascript:void(0)" role="button" data-toggle="dropdown">
                                    <img src="{{user.image_url}}" width="20" alt=""/>
									<div class="header-info">
										<span class="text-black"><strong>{{user.name}}</strong></span>
										<p class="fs-12 mb-0">{{user.user_type}}</p>
									</div>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right">
                                    <a href="#.html" class="dropdown-item ai-icon">
                                        <svg id="icon-user1" xmlns="http://www.w3.org/2000/svg" class="text-primary" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path><circle cx="12" cy="7" r="4"></circle></svg>
                                        <span class="ml-2">Profile </span>
                                    </a>
                                    <a href="#.html" class="dropdown-item ai-icon">
                                        <svg id="icon-inbox" xmlns="http://www.w3.org/2000/svg" class="text-success" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"></path><polyline points="22,6 12,13 2,6"></polyline></svg>
                                        <span class="ml-2">Inbox </span>
                                    </a>
                                    <a href="{% url 'logout' %}" class="dropdown-item ai-icon">
                                        <svg id="icon-logout" xmlns="http://www.w3.org/2000/svg" class="text-danger" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"></path><polyline points="16 17 21 12 16 7"></polyline><line x1="21" y1="12" x2="9" y2="12"></line></svg>
                                        <span class="ml-2">Logout </span>
                                    </a>
                                </div>
                            </li>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
        <!--**********************************
            Header end ti-comment-alt
        ***********************************-->

        <!--**********************************
            Sidebar start
        ***********************************-->
        <div class="deznav">
            <div class="deznav-scroll">
				<ul class="metismenu" id="menu">
                    <li><a class="ai-icon" href="{% url 'dashboard' %}" aria-expanded="false">
							<i class="flaticon-381-networking"></i>
							<span class="nav-text">Dashboard</span>
						</a>
                    </li>
                    <li><a class="ai-icon" href="{% url 'customers' %}" aria-expanded="false">
							<i class="flaticon-381-user-3"></i>
							<span class="nav-text">Customers</span>
						</a>
                    </li>
                    {% comment %} <li><a class="ai-icon" href="{% url 'recipe_management' %}" aria-expanded="false">
							<i class="flaticon-381-controls-3"></i>
							<span class="nav-text">Recipe Management</span>
						</a>
                    </li> {% endcomment %}
					 <li><a class="has-arrow ai-icon" href="javascript:void()" aria-expanded="false">
							<i class="flaticon-381-calculator"></i>
							<span class="nav-text">Recipe Management</span>
						</a>
                       <ul aria-expanded="false" class="mm-collapse mm-show" style="">
                            <li><a href="{% url 'recipe_management' %}">Recipe</a></li>
                            <li><a href="{% url 'ingredient_items' %}">Ingredients</a></li>
                        </ul>
                    </li>
                </ul>
				<!-- <div class="add-menu-sidebar"> -->
					<!-- <img src="{% static 'images/calendar.png' %}" alt="" class="mr-3"> -->
					<!-- <p class="	font-w500 mb-0">Create Workout Plan Now</p> -->
				<!-- </div> -->
			</div>
        </div>
        <!--**********************************
            Sidebar end
        ***********************************-->
		
		<!--**********************************
            Content body start
        ***********************************-->
        {% block content %}{% endblock  %}
        
        <!--**********************************
            Content body end
        ***********************************-->

        <!--**********************************
            Footer start
        ***********************************-->
        <div class="footer">
            <div class="copyright">
                <p>©2023-Fit4LifeIndia All Rights Reserved. </p>
            </div>
        </div>
        <!--**********************************
            Footer end
        ***********************************-->

		<!--**********************************
           Support ticket button start
        ***********************************-->

        <!--**********************************
           Support ticket button end
        ***********************************-->


    </div>
    <!--**********************************
        Main wrapper end
    ***********************************-->

    <!--**********************************
        Scripts
    ***********************************-->
    <!-- Required vendors -->
    <script src="/static/vendor/global/global.min.js"></script>
	<script src="/static/vendor/bootstrap-select/dist/js/bootstrap-select.min.js"></script>
	<script src="/static/vendor/chart.js/Chart.bundle.min.js"></script>
    <script src="/static/js/custom.min.js"></script>
	<script src="/static/js/deznav-init.js"></script>
	
    <!-- Datatable -->
    <script src="/static/vendor/datatables/js/jquery.dataTables.min.js"></script>
    <script src="/static/js/plugins-init/datatables.init.js"></script>
    <script src="vendor/highlightjs/highlight.pack.min.js"></script>
	<script src="vendor/star-rating/jquery.star-rating-svg.js"></script>
	
	<!-- Chart piety plugin files -->
    <script src="/static/vendor/peity/jquery.peity.min.js"></script>
	
	<!-- Apex Chart -->
	<script src="/static/vendor/apexchart/apexchart.js"></script>
	<script src="/static/js/plugins-init/morris-init.js"></script>

	
	<!-- Dashboard 1 -->
	<script src="/static/js/dashboard/dashboard-1.js"></script>
	<script>
		function carouselReview(){
			/*  testimonial one function by = owl.carousel.js */
			jQuery('.testimonial-one').owlCarousel({
				loop:true,
				autoplay:true,
				margin:30,
				nav:false,
				dots: false,
				left:true,
				navText: ['<i class="fa fa-chevron-left" aria-hidden="true"></i>', '<i class="fa fa-chevron-right" aria-hidden="true"></i>'],
				responsive:{
					0:{
						items:1
					},
					484:{
						items:2
					},
					882:{
						items:3
					},	
					1200:{
						items:2
					},			
					
					1540:{
						items:3
					},
					1740:{
						items:4
					}
				}
			})			
		}
		jQuery(window).on('load',function(){
			setTimeout(function(){
				carouselReview();
			}, 1000); 
		});
	</script>
    <script>
        {% block js %}{% endblock  %}
    </script>
</body>
</body>
</html>

templates/customers-datatable.html
{% extends 'base.html' %}
{% block css %}{% endblock %}
{% block js %}{% endblock  %}
{% block content %}
        <div class="content-body">
            <div class="container-fluid">
                <div class="page-titles">
					<ol class="breadcrumb">
						<li class="breadcrumb-item"><a href="javascript:void(0)">Customers</a></li>
						<li class="breadcrumb-item active"><a href="javascript:void(0)">Table</a></li>
					</ol>
                </div>
                <!-- row -->


                <div class="row">
					<div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <h4 class="card-title">Customers</h4>
                                <a href="{% url 'add_customer' %}"> <button type="button" class="btn btn-primary">Add New Customer</button></a>
                            </div>
                            
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table id="example5" class="display min-w850">
                                        <thead>
                                            <tr>
                                                <th>ID</th>
                                                <th>Date</th>
                                                <th>Name</th>
                                                <th>Age</th>
                                                <th>Gender</th>
                                                <th>Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for d in data %}
                                            {% comment %} {% if user.role != "admin" %} {% endcomment %}
                                            <tr>
                                               
                                                <td style="text-align: left;">DCFL{{forloop.counter}}</td>
                                                <td style="text-align: left;">{{d.date}}</td>
                                                <td style="text-align: left;">{{d.first_name}}&nbsp;{{d.last_name}}</td>
                                                <td style="text-align: left;">{{d.age}}</td>
                                                <td style="text-align: left;">{{d.gender}}</td>
                                                {% comment %} <td>{{d.action}}</td> {% endcomment %}
                                                
                                                <td style="text-align: left;">
													<div class="d-flex justify-content-left">
														<a href="{% url 'customers_detail' d.id %}" class="btn btn-primary shadow btn-xs sharp mr-1"><i class="fa fa-eye"></i></a>
													</div>
												</td>												
                                            </tr>
                                            {% comment %} {% endif %} {% endcomment %}
                                            {% endfor %}
                                            
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            
                        </div>
                    </div>
				</div>
            </div>
        </div>
    {% endblock  %}

templates/page-forgot-password.html
<!DOCTYPE html>
<html lang="en" class="h-100">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Fit4LifeIndia Admin Dashboard</title>
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="images/favicon.png">
    <link href="css/style.css" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&amp;family=Roboto:wght@100;300;400;500;700;900&amp;display=swap" rel="stylesheet">
</head>

<body class="h-100">
    <div class="authincation h-100">
        <div class="container h-100">
            <div class="row justify-content-center h-100 align-items-center">
                <div class="col-md-6">
                    <div class="authincation-content">
                        <div class="row no-gutters">
                            <div class="col-xl-12">
                                <div class="auth-form">
									<div class="text-center mb-3">
										<img src="images/logo.png" alt=""></a>
									</div>
                                    <h4 class="text-center mb-4 text-white">Forgot Password</h4>
                                    <form action="{% url 'dashboard' %}">
                                        <div class="form-group">
                                            <label class="" style="color:#554848 !important;"><strong>Email</strong></label>
                                            <input type="email" class="form-control" value="hello@example.com">
                                        </div>
                                        <div class="text-center">
                                            <button type="submit" class="btn bg-blue text-primary btn-block" style="color:#FFF !important;">SUBMIT</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <!--**********************************
        Scripts
    ***********************************-->
    <!-- Required vendors -->
    <script src="vendor/global/global.min.js"></script>
	<script src="vendor/bootstrap-select/dist/js/bootstrap-select.min.js"></script>
    <script src="js/custom.min.js"></script>
    <script src="js/deznav-init.js"></script>

</body>
</html>

templates/recipe.html
{% extends 'base.html' %}
{% block css %}{% endblock %}
{% block js %}{% endblock  %}
{% block content %}
        <div class="content-body">
            <div class="container-fluid">
                <div class="page-titles">
					<ol class="breadcrumb">
						<li class="breadcrumb-item"><a href="javascript:void(0)">Customers</a></li>
						<li class="breadcrumb-item active"><a href="javascript:void(0)">Table</a></li>
					</ol>
                </div>
                <!-- row -->


                <div class="row">
					<div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <h4 class="card-title">Customers</h4>
                                <a href="{% url 'add_recipe' %}"> <button type="button" class="btn btn-primary">+Add Customer</button></a>
                            </div>
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table id="example5" class="display min-w850">
                                        <thead>
                                            <tr>
                                                <th>ID</th>
                                                <th>Item Name</th>
                                                <th>Sub Name</th>
                                                <th>Type Of Meal</th>
                                                <th>Type Of Food</th>
                                                <th>Ingredients</th>
                                                <th>Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for d in all_recipe %}
                                            <tr>
                                               
                                                <td>{{d.id}}</td>
                                                <td>{{d.item_name}}</td>
                                                <td>{{d.sub_name}}</td>
                                                <td>{{d.type_of_meal}}</td>
                                                <td>{{d.type_of_food}}</td>
                                                <td>
                                                    <!-- Loop through the related ingredients for this recipe -->
                                                    {% for ingridient in d.addingridient_set.all %}
                                                        {{ ingridient.ingridient_name }},
                                                    {% endfor %}
                                                </td>
                                                
                                                <td>
													<div class="d-flex">
														<a href="{% url 'recipe_details' d.id %}" class="btn btn-primary shadow btn-xs sharp mr-1"><i class="fa fa-eye"></i></a>
													</div>
												</td>												
                                            </tr>
                                            {% endfor %}
                                            
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
				</div>
            </div>
        </div>
    {% endblock  %}